assetDir = 'static'
baseURL = 'https://michaelpys.com'
languageCode = 'en-us'
title = 'Michael Pys Headache and Pain Center'
disableKinds = ['taxonomy']
canonifyurls = true
enableRobotsTXT = true
[markup.goldmark.renderer]
    unsafe = true 
[services]
  [services.googleAnalytics]
    id = 'G-NPD4MKHW4K'
[params]
keywords = "headaches, migranes, chronic pain, pain center"
description = "Default site description"