assetDir = 'static'
baseURL = 'https://michaelpys.com'
languageCode = 'en-us'
title = 'Micheal Pys Headache and Pain Center'
disableKinds = ['taxonomy']
canonifyurls = true
[markup.goldmark.renderer]
    unsafe = true 
